version: "3.5"
services:
  atlas-file-service-web-2:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ${ENV_FLASK_HOME}:/code
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - MINIO_ACCESS_KEY=${ENV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${ENV_MINIO_SECRET_KEY}
      - MINIO_URL=${ENV_MINIO_URL}
      - BUCKET_NAME=${ENV_BUCKET_NAME}
    networks:
      local:
        aliases:
          - atlas-file-service-web
  redis:
    image: redis
    networks:
      local:
        aliases:
          - redis
    
  minio-s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${ENV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${ENV_MINIO_SECRET_KEY}
    command: gateway s3
    networks:
      local:
        aliases:
          - minio-s3
          
volumes:
  atlas-file-service:
    driver: local
          
networks:
  local:
    name: atlas-file-service
    
